-- create database customer_behaviour;
use customer_behaviour;
select*from customer limit 10;

-- Q1. What is the total revenue generated by male vs. female customers?

select gender , sum(purchase_amount) as revenue from customer
group by gender ;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount from customer
where discount_applied="Yes" and purchase_amount >=(select avg(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg (review_rating),2) as average_review_rating 
from customer 
group by item_purchased 
order by average_review_rating desc 
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount) as avg_purchase_amount from customer
where shipping_type in ('Standard','Express')
group by shipping_type ;


 -- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
 -- between subscribers and non-subscribers
 
 select subscription_status , avg(purchase_amount) as avg_purchase_amount , 
 sum(purchase_amount) as total_revenue, count(customer_id) as total_customer
 from customer 
 group by  subscription_status;
 

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied

select item_purchased , 
100 * sum( case when discount_applied="Yes"then 1 else 0 end )/count(*) as percentage_discount_applied 
from customer 
group by item_purchased
order by percentage_discount_applied desc
limit 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
select customer_id, previous_purchases , 
case when previous_purchases =1 then "New"
	 when previous_purchases between 2 and 10 then "returning" 
     else "Loyal" end as customer_segment
from customer
)
select customer_segment,count(*) as no_of_cus
from customer_type
group by customer_segment;


		
-- Q8. What are the top 3 most purchased products within each category? 
with cus as (
select item_purchased ,category,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc ) as item_rank
from customer
group by category, item_purchased

)
select  item_rank, item_purchased,total_orders,category
from cus
where item_rank<=3;



-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, 
count(customer_id) as total_cus
from customer
where previous_purchases>5
group by subscription_status ;


-- Q10. What is the revenue contribution of each age group? 

select sum(purchase_amount),age_group from customer 
group by age_group



